name: Build and Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Set environment variables for Windows
        if: matrix.os == 'windows-latest'
        run: echo "NODE_OPTIONS=--openssl-legacy-provider --experimental-global-webcrypto" >> $GITHUB_ENV
        shell: bash

      # Add global environment variables for non-Windows platforms        
      - name: Setup crypto polyfill for non-Windows
        if: matrix.os != 'windows-latest'
        run: echo "NODE_OPTIONS=--experimental-global-webcrypto" >> $GITHUB_ENV
        shell: bash
      
      - name: Build/Publish Electron App
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Remove the --no-experimental-fetch flag which might be causing issues
          # NODE_OPTIONS: --no-experimental-fetch 